Category.create(name:"ファッション")
Category.create(name:"デジタル")
Category.create(name:"コスメ")
Category.create(name:"キッチン")
Category.create(name:"暮らし")
Category.create(name:"その他")


Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)
Post.create(content: 'おすすめの財布',category_id:1, image: open("#{Rails.root}/db/fixtures/img.jpg"),user_id:1)